export const COMMENTS_REPOSITORY = 'COMMENTS_REPOSITORY';
export const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY';
export const PARTIDO_REPOSITORY = 'PARTIDO_REPOSITORY';
export const FEED_REPOSITORY = 'FEED_REPOSITORY';